### ISSUE TITLE
Link to SonarQube is no longer working.

### ISSUE THREAD

**Issue by JeneJasper** [SonarQubeCommunity/sonar-maven-report#6]
See pull request https://github.com/SonarQubeCommunity/sonar-maven-report/pull/5

**Comment by JeneJasper** [comment]
@simonbrandhof Who can assign this issue to?

**Comment by bob-rohan** [comment]
@JeneJasper thanks for the fix. 

There is a potential longer term solution to future proof against further url changes, and move away from hardcoding this value. We could make use of the dashboardUrl key-value pair produced by sonar in report-task.txt (target/sonar/report-task.txt)

**Comment by JeneJasper** [comment]
But that only works if `sonar:sonar` is invoked before `site site:stage` in case of GitLab CI `pages` or `site-deploy` in case of Jenkins CI. 

Alas those jobs run in parallel on my `.gitlab-ci.yml` and`Jenkinsfile` job configurations.

**Comment by simonbrandhof** [comment]
Hi @JeneJasper sorry for the late answer. To make things simpler, would you be ready to take the ownership of this project and to get the write permissions? I'm afraid I don't have enough time to devote to myself to it.

**Comment by JeneJasper** [comment]
Since every thing is building and the posted issues are mine that might be a feasible solution.

**Comment by simonbrandhof** [comment]
@JeneJasper invitation sent. Thank you very much.

**Comment by JeneJasper** [comment]
Thanks for the invite.

I have one question about the release process. The Travis build runs verify. How is the plugin released to the Maven repository?

And what are the average queue times for Travis : )
  Apperently Travis build server was faulty four several hours.
